### ISSUE TITLE
Temperature not published

### ISSUE THREAD

**Issue by 130s** [130s/computer_monitor#1]
```
# rostopic echo /diagnostics
header: 
  seq: 1
  stamp: 
    secs: 1600067095
    nsecs: 220305919
  frame_id: ''
status: 
  - 
    level: 2
    name: "GPU Status"
    message: "No Device Data"
    hardware_id: ''
    values: 
      - 
        key: "Product Name"
        value: "GeForce GTX 1060 6GB"
      - 
        key: "PCI Device/Vendor ID"
        value: ''
      - 
        key: "PCI Location ID"
        value: ''
      - 
        key: "Display"
        value: ''
      - 
        key: "Driver Version"
        value: "440.64"
      - 
        key: "Temperature (C)"
        value: "0"
      - 
        key: "Fan Speed (RPM)"
        value: "1215"
      - 
        key: "Usage (%)"
        value: "0"
      - 
        key: "Memory (%)"
        value: "13"
```
But temp is listed when I directly hit the command:
```
sudo nvidia-smi -a
:
    Temperature
        GPU Current Temp            : 55 C
        GPU Shutdown Temp           : 102 C
        GPU Slowdown Temp           : 99 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
```
Assuming https://askubuntu.com/questions/685017/how-to-install-nvidia-smi is right, `nvidia-smi` is provided by nvidia-X pkg,
```
$ apt-cache policy nvidia-container-toolkit
nvidia-container-toolkit:
  Installed: 1.0.5-1
  Candidate: 1.2.1-1
```
